repos:
  - repo: https://github.com/grantjenks/blue
    rev: v0.9.1
    hooks:
      - id: blue
        name: blue formatter
        entry: python -m blue
        language: python
        types: [python]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4  # importante!
    hooks:
      - id: ruff
        name: ruff lint
        entry: ruff check
        language: python
        args: [--fix]
        types: [python]
  

  - repo: https://github.com/pre-commit/mirrors-mypy
    # Verificação de type hints
    rev: v1.5.1
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
        entry: python -m mypy
        language: system

  # Bandit usando python -m para evitar o .EXE bloqueado
  - repo: local
    hooks:
      - id: bandit-local
        name: bandit security checks
        entry: python -m bandit
        language: system
        args: ["-q", "--confidence-level", "low"]
        types: [python]