repos:
  - repo: local
    hooks:
      - id: blue
        name: blue formatter
        entry: blue
        language: python
        types: [python]

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff lint
        entry: ruff
        language: python
        args: [ --fix ]
        types: [python]
  

  - repo: https://github.com/pre-commit/mirrors-mypy
    # Verificação de type hints
    rev: v1.5.1
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]

  - repo: https://github.com/PyCQA/bandit
    # Serve para verificar padrões de código sem seguranca
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-q", "--confidence-level", "LOW"]
      