[tool.ruff]
target-version = "py312" 
fix = true
show-fixes = true

select = [
  "E",    # pycodestyle (PEP8)
  "F",    # pyflakes
  "I",    # isort (organização de imports)
  "UP",   # pyupgrade
  "B",    # flake8-bugbear
]

[tool.ruff.format]
quote-style = "single"  

[tool.black]
line-lenght = 79
include = '\.piy?$'
exclude = '''
/(
  \.git
 | \.hg
 | \.mypy_cache
 | \.tox
 | \.venv
 | _build
 | buck-out
 | build
 | .__pycache__
 )/
'''
