[tool.ruff]
target-version = "py312" 
fix = true
show-fixes = true

select = [
  "E",    # pycodestyle (PEP8)
  "F",    # pyflakes
  "I",    # isort (organização de imports)
  "UP",   # pyupgrade
  "B",    # flake8-bugbear
]

[tool.ruff.format]
quote-style = "single"  

[tool.blue]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
  \.git
 | \.hg
 | \.mypy_cache
 | \.tox
 | \.venv
 | _build
 | buck-out
 | build
 | __pycache__
 | \.pytest_cache
 | \.coverage
)/
'''


[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function" 
testpaths = ["tests"]
python_files = ["testa_*.py", "*_testa.py"]
python_classes = ["Testa*"]
python_functions = ["testa_*"]
addopts = """
    --strict-markers 
    --tb=short 
    --maxfail=1 
    --cov=api_presentation
    --cov=application_service
    --cov=domain_entity
    --cov=infra_repository
    --cov-report=term-missing
     
"""
markers = [
  "slow: testes lentos",
  "integration: testes de integração"
]