server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml  # Rastreia posição nos logs

clients:
  - url: http://loki:3100/loki/api/v1/push  # URL do Loki

scrape_configs:
- job_name: docker
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
      filters:
        - name: label
          values: ["logging=promtail"]  # Filtra containers com esta label
  
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'  # Extrai nome do container
      target_label: 'container'
    - source_labels: ['__meta_docker_container_log_stream']
      target_label: 'logstream'